### ISSUE TITLE
Parsing JSON with doubles as value :bug:

### ISSUE THREAD

**Issue by thomastloberg** [dday9/.NET-JSON-Transformer#4]
Hi!
I found a "bug" in the code.
If you parse a json string with the culture.NumberFormat.NumberDecimalSeparator in Norway it will generate an error. Because we usualy use comma (,) and not dot (.) to seperate decimals. But in most computers in general it's used dot (.).
Would recommend to change this to US / World Standard. :)

culture.NumberFormat.NumberDecimalSeparator  => "."

Line 335

**Comment by dday9** [comment]
@thomastloberg  - The code works based on the CurrentCulture. So if your operating system is set to a culture that uses a comma as the decimal place (e.g. `nn-NO`) then it would work. However, I did modify the code to take an optional CultureInfo parameter so that you can manually specify the culture. See this example: https://dotnetfiddle.net/r87ajE
